bpf: verifier: remove redundant check for array member log->kbuf
Clang warns that taking the address of array member 'log->kbuf'
will always evaluate to true:

    error: address of array 'log->kbuf' will always evaluate to 'true'
           [-Werror,-Wpointer-bool-conversion]

Since 'log->kbuf' is a fixed-size array within 'struct bpf_verifier_log',
its address is guaranteed to be non-NULL, making the check redundant.

Remove the unnecessary 'log->kbuf' condition to fix the build
with clang and -Werror.

Signed-off-by: ApartTUSITU <aptusitu@outlook.com>